/* lakara.c — laṭ tiṅ table utilities; Story 3.3 */
#include "lakara.h"
#include <string.h>

static const TingEntry LAT_PARASMAI[9] = {
    {ASH_LAT, ASH_PRATHAMA, ASH_EKAVACANA, ASH_PARASMAI, "tip", "ti", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_PRATHAMA, ASH_DVIVACANA, ASH_PARASMAI, "tas", "tas", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_PRATHAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ji", "anti", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_MADHYAMA, ASH_EKAVACANA, ASH_PARASMAI, "sip", "si", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_MADHYAMA, ASH_DVIVACANA, ASH_PARASMAI, "Tas", "Tas", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_MADHYAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ta", "Ta", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_UTTAMA, ASH_EKAVACANA, ASH_PARASMAI, "mip", "mi", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_UTTAMA, ASH_DVIVACANA, ASH_PARASMAI, "vas", "vas", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_UTTAMA, ASH_BAHUVACANA, ASH_PARASMAI, "mas", "mas", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
};

static const TingEntry LAT_ATMANE[9] = {
    {ASH_LAT, ASH_PRATHAMA, ASH_EKAVACANA, ASH_ATMANE, "ta", "te", SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_PRATHAMA, ASH_DVIVACANA, ASH_ATMANE, "AtAm", "Ate", SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_PRATHAMA, ASH_BAHUVACANA, ASH_ATMANE, "Ja", "ante", SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_MADHYAMA, ASH_EKAVACANA, ASH_ATMANE, "TAs", "se", SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_MADHYAMA, ASH_DVIVACANA, ASH_ATMANE, "ATAm", "ATe", SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_MADHYAMA, ASH_BAHUVACANA, ASH_ATMANE, "Dvam", "Dve", SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_UTTAMA, ASH_EKAVACANA, ASH_ATMANE, "iw", "e", SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_UTTAMA, ASH_DVIVACANA, ASH_ATMANE, "vahi", "vahe", SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_UTTAMA, ASH_BAHUVACANA, ASH_ATMANE, "mahiN", "mahe", SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
};

/* LAN (imperfect) — secondary endings, ṅit by 3.4.99 nityaṃ ṅitaḥ.
   Per 3.4.100 itaś ca, the final i of secondary endings is dropped.
   The a-augment is prepended at form-build time (6.4.71). */
static const TingEntry LAN_PARASMAI[9] = {
    {ASH_LAN, ASH_PRATHAMA, ASH_EKAVACANA, ASH_PARASMAI, "tip", "t", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAN, ASH_PRATHAMA, ASH_DVIVACANA, ASH_PARASMAI, "tas", "tAm", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAN, ASH_PRATHAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ji", "an", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAN, ASH_MADHYAMA, ASH_EKAVACANA, ASH_PARASMAI, "sip", "H", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAN, ASH_MADHYAMA, ASH_DVIVACANA, ASH_PARASMAI, "Tas", "tam", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAN, ASH_MADHYAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ta", "ta", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAN, ASH_UTTAMA, ASH_EKAVACANA, ASH_PARASMAI, "mip", "am", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAN, ASH_UTTAMA, ASH_DVIVACANA, ASH_PARASMAI, "vas", "va", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAN, ASH_UTTAMA, ASH_BAHUVACANA, ASH_PARASMAI, "mas", "ma", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
};

/* LOT (imperative) — Story 3.21. Endings per 3.4.86–96 substitutions. */
static const TingEntry LOT_PARASMAI[9] = {
    {ASH_LOT, ASH_PRATHAMA, ASH_EKAVACANA, ASH_PARASMAI, "tu", "tu", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LOT, ASH_PRATHAMA, ASH_DVIVACANA, ASH_PARASMAI, "tAm", "tAm", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LOT, ASH_PRATHAMA, ASH_BAHUVACANA, ASH_PARASMAI, "antu", "antu", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    /* madhyama-eka: 3.4.91 seḥ hi → "hi" but realised as "" (zero) for vowel-final stems. */
    {ASH_LOT, ASH_MADHYAMA, ASH_EKAVACANA, ASH_PARASMAI, "hi", "", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LOT, ASH_MADHYAMA, ASH_DVIVACANA, ASH_PARASMAI, "tam", "tam", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LOT, ASH_MADHYAMA, ASH_BAHUVACANA, ASH_PARASMAI, "ta", "ta", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LOT, ASH_UTTAMA, ASH_EKAVACANA, ASH_PARASMAI, "Ani", "Ani", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LOT, ASH_UTTAMA, ASH_DVIVACANA, ASH_PARASMAI, "Ava", "Ava", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LOT, ASH_UTTAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ama", "Ama", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
};

/* VIDHILIN (optative) — Story 3.22. yāsuṭ in singular, ī in dual/plural;
   the table here records the ending after yA/I has been merged with the
   tiṅ. For thematic stems the result simplifies to e+secondary. */
static const TingEntry VIDHILIN_PARASMAI[9] = {
    {ASH_VIDHILIM, ASH_PRATHAMA, ASH_EKAVACANA, ASH_PARASMAI, "yAt", "et", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_VIDHILIM, ASH_PRATHAMA, ASH_DVIVACANA, ASH_PARASMAI, "yAtAm", "etAm", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_VIDHILIM, ASH_PRATHAMA, ASH_BAHUVACANA, ASH_PARASMAI, "yur", "eyuH", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_VIDHILIM, ASH_MADHYAMA, ASH_EKAVACANA, ASH_PARASMAI, "yAH", "eH", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_VIDHILIM, ASH_MADHYAMA, ASH_DVIVACANA, ASH_PARASMAI, "yAtam", "etam", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_VIDHILIM, ASH_MADHYAMA, ASH_BAHUVACANA, ASH_PARASMAI, "yAta", "eta", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_VIDHILIM, ASH_UTTAMA, ASH_EKAVACANA, ASH_PARASMAI, "yAm", "eyam", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_VIDHILIM, ASH_UTTAMA, ASH_DVIVACANA, ASH_PARASMAI, "yAva", "eva", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_VIDHILIM, ASH_UTTAMA, ASH_BAHUVACANA, ASH_PARASMAI, "yAma", "ema", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
};

/* LUT (periphrastic future) — Story 3.19. The endings absorb the
   tās augment so that the "stem" passed in only needs the root + iṭ.
   3.4.78 also substitutes specific upadeśa endings for prathama
   (DA, rau, ras → A, ArO, AraH). */
static const TingEntry LUT_PARASMAI[9] = {
    {ASH_LUT, ASH_PRATHAMA, ASH_EKAVACANA, ASH_PARASMAI, "DA", "tA", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LUT, ASH_PRATHAMA, ASH_DVIVACANA, ASH_PARASMAI, "rO", "tArO", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LUT, ASH_PRATHAMA, ASH_BAHUVACANA, ASH_PARASMAI, "raH", "tAraH", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LUT, ASH_MADHYAMA, ASH_EKAVACANA, ASH_PARASMAI, "sip", "tAsi", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LUT, ASH_MADHYAMA, ASH_DVIVACANA, ASH_PARASMAI, "Tas", "tAsTaH", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LUT, ASH_MADHYAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ta", "tAsTa", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LUT, ASH_UTTAMA, ASH_EKAVACANA, ASH_PARASMAI, "mip", "tAsmi", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LUT, ASH_UTTAMA, ASH_DVIVACANA, ASH_PARASMAI, "vas", "tAsvaH", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LUT, ASH_UTTAMA, ASH_BAHUVACANA, ASH_PARASMAI, "mas", "tAsmaH", SJ_TING | SJ_PARASMAIPADA},
};

/* LRN (conditional) — Story 3.25. Combines LRT's sya stem with LAN's
   secondary endings + a-augment. Endings = LAN secondary endings. */
static const TingEntry LRN_PARASMAI[9] = {
    {ASH_LRN, ASH_PRATHAMA, ASH_EKAVACANA, ASH_PARASMAI, "tip", "t", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRN, ASH_PRATHAMA, ASH_DVIVACANA, ASH_PARASMAI, "tas", "tAm", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRN, ASH_PRATHAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ji", "an", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRN, ASH_MADHYAMA, ASH_EKAVACANA, ASH_PARASMAI, "sip", "H", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRN, ASH_MADHYAMA, ASH_DVIVACANA, ASH_PARASMAI, "Tas", "tam", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRN, ASH_MADHYAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ta", "ta", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRN, ASH_UTTAMA, ASH_EKAVACANA, ASH_PARASMAI, "mip", "am", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRN, ASH_UTTAMA, ASH_DVIVACANA, ASH_PARASMAI, "vas", "va", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRN, ASH_UTTAMA, ASH_BAHUVACANA, ASH_PARASMAI, "mas", "ma", SJ_TING | SJ_PARASMAIPADA},
};

/* ASIRLIN (benedictive) — Story 3.23. yāsuṭ + sIyuṭ + secondary
   endings. The stem is bare root (suffix is kit, blocks guṇa). */
static const TingEntry ASIRLIN_PARASMAI[9] = {
    {ASH_ASHIRLIM, ASH_PRATHAMA, ASH_EKAVACANA, ASH_PARASMAI, "tip", "yAt", SJ_TING | SJ_PARASMAIPADA},
    {ASH_ASHIRLIM, ASH_PRATHAMA, ASH_DVIVACANA, ASH_PARASMAI, "tas", "yAstAm", SJ_TING | SJ_PARASMAIPADA},
    {ASH_ASHIRLIM, ASH_PRATHAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ji", "yAsuH", SJ_TING | SJ_PARASMAIPADA},
    {ASH_ASHIRLIM, ASH_MADHYAMA, ASH_EKAVACANA, ASH_PARASMAI, "sip", "yAH", SJ_TING | SJ_PARASMAIPADA},
    {ASH_ASHIRLIM, ASH_MADHYAMA, ASH_DVIVACANA, ASH_PARASMAI, "Tas", "yAstam", SJ_TING | SJ_PARASMAIPADA},
    {ASH_ASHIRLIM, ASH_MADHYAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ta", "yAsta", SJ_TING | SJ_PARASMAIPADA},
    {ASH_ASHIRLIM, ASH_UTTAMA, ASH_EKAVACANA, ASH_PARASMAI, "mip", "yAsam", SJ_TING | SJ_PARASMAIPADA},
    {ASH_ASHIRLIM, ASH_UTTAMA, ASH_DVIVACANA, ASH_PARASMAI, "vas", "yAsva", SJ_TING | SJ_PARASMAIPADA},
    {ASH_ASHIRLIM, ASH_UTTAMA, ASH_BAHUVACANA, ASH_PARASMAI, "mas", "yAsma", SJ_TING | SJ_PARASMAIPADA},
};

/* LRT (simple future) — Story 3.20. Same endings as LAT (primary). */
static const TingEntry LRT_PARASMAI[9] = {
    {ASH_LRT, ASH_PRATHAMA, ASH_EKAVACANA, ASH_PARASMAI, "tip", "ti", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRT, ASH_PRATHAMA, ASH_DVIVACANA, ASH_PARASMAI, "tas", "tas", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRT, ASH_PRATHAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ji", "anti", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRT, ASH_MADHYAMA, ASH_EKAVACANA, ASH_PARASMAI, "sip", "si", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRT, ASH_MADHYAMA, ASH_DVIVACANA, ASH_PARASMAI, "Tas", "Tas", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRT, ASH_MADHYAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ta", "Ta", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRT, ASH_UTTAMA, ASH_EKAVACANA, ASH_PARASMAI, "mip", "mi", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRT, ASH_UTTAMA, ASH_DVIVACANA, ASH_PARASMAI, "vas", "vas", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRT, ASH_UTTAMA, ASH_BAHUVACANA, ASH_PARASMAI, "mas", "mas", SJ_TING | SJ_PARASMAIPADA},
};

static int ting_index(ASH_Purusha p, ASH_Vacana v) {
  return ((int)p * 3) + (int)v;
}

const TingEntry *ting_get(ASH_Lakara l, ASH_Purusha p, ASH_Vacana v, ASH_Pada pd) {
  if (p > ASH_UTTAMA || v > ASH_BAHUVACANA) return NULL;
  int idx = ting_index(p, v);
  if (idx < 0 || idx >= 9) return NULL;
  if (pd == ASH_ATMANE && l == ASH_LAT) return &LAT_ATMANE[idx];
  switch (l) {
    case ASH_LAT:      return &LAT_PARASMAI[idx];
    case ASH_LAN:      return &LAN_PARASMAI[idx];
    case ASH_LOT:      return &LOT_PARASMAI[idx];
    case ASH_VIDHILIM: return &VIDHILIN_PARASMAI[idx];
    case ASH_LRT:      return &LRT_PARASMAI[idx];
    case ASH_LUT:      return &LUT_PARASMAI[idx];
    case ASH_LRN:      return &LRN_PARASMAI[idx];
    case ASH_ASHIRLIM:  return &ASIRLIN_PARASMAI[idx];
    default: return NULL;
  }
}

int ting_assign(PrakriyaCtx *ctx, ASH_Lakara l, ASH_Purusha p, ASH_Vacana v, ASH_Pada pd) {
  if (!ctx || ctx->term_count >= MAX_TERMS) return -1;
  const TingEntry *t = ting_get(l, p, v, pd);
  if (!t) return -1;

  Term *dst = &ctx->terms[ctx->term_count];
  term_init(dst, t->upadesa, SJ_PRATYAYA | SJ_TING);
  dst->samjna = samjna_add(dst->samjna, t->samjna);

  /* Ensure the clean form matches our target table for determinism. */
  strncpy(dst->value, t->clean, TERM_VALUE_LEN - 1);
  dst->value[TERM_VALUE_LEN - 1] = '\0';

  ctx->term_count++;
  return 0;
}

bool lakara_is_sarvadhatuka(ASH_Lakara l) {
  return (l == ASH_LAT || l == ASH_LOT || l == ASH_LAN || l == ASH_VIDHILIM);
}

const char *lakara_name(ASH_Lakara l) {
  static const char *const names[] = {
      "laT", "liT", "luT", "lfT", "loT", "laN", "viDiliN", "ASIrliN", "luN", "lfN"};
  if (l < 0 || l >= ASH_LAKARA_COUNT) return "unknown";
  return names[(int)l];
}
