/* lakara.c — laṭ tiṅ table utilities; Story 3.3 */
#include "lakara.h"
#include <string.h>

static const TingEntry LAT_PARASMAI[9] = {
    {ASH_LAT, ASH_PRATHAMA, ASH_EKAVACANA, ASH_PARASMAI, "tip", "ti", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_PRATHAMA, ASH_DVIVACANA, ASH_PARASMAI, "tas", "tas", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_PRATHAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ji", "anti", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_MADHYAMA, ASH_EKAVACANA, ASH_PARASMAI, "sip", "si", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_MADHYAMA, ASH_DVIVACANA, ASH_PARASMAI, "Tas", "Tas", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_MADHYAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ta", "Ta", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_UTTAMA, ASH_EKAVACANA, ASH_PARASMAI, "mip", "mi", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_UTTAMA, ASH_DVIVACANA, ASH_PARASMAI, "vas", "vas", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_UTTAMA, ASH_BAHUVACANA, ASH_PARASMAI, "mas", "mas", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
};

static const TingEntry LAT_ATMANE[9] = {
    {ASH_LAT, ASH_PRATHAMA, ASH_EKAVACANA, ASH_ATMANE, "ta", "te", SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_PRATHAMA, ASH_DVIVACANA, ASH_ATMANE, "AtAm", "ete", SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_PRATHAMA, ASH_BAHUVACANA, ASH_ATMANE, "Ja", "ante", SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_MADHYAMA, ASH_EKAVACANA, ASH_ATMANE, "TAs", "se", SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_MADHYAMA, ASH_DVIVACANA, ASH_ATMANE, "ATAm", "eTe", SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_MADHYAMA, ASH_BAHUVACANA, ASH_ATMANE, "Dvam", "Dve", SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_UTTAMA, ASH_EKAVACANA, ASH_ATMANE, "iw", "e", SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_UTTAMA, ASH_DVIVACANA, ASH_ATMANE, "vahi", "vahe", SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LAT, ASH_UTTAMA, ASH_BAHUVACANA, ASH_ATMANE, "mahiN", "mahe", SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
};

/* LAN (imperfect) — secondary endings, ṅit by 3.4.99 nityaṃ ṅitaḥ.
   Per 3.4.100 itaś ca, the final i of secondary endings is dropped.
   The a-augment is prepended at form-build time (6.4.71). */
static const TingEntry LAN_PARASMAI[9] = {
    {ASH_LAN, ASH_PRATHAMA, ASH_EKAVACANA, ASH_PARASMAI, "tip", "t", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAN, ASH_PRATHAMA, ASH_DVIVACANA, ASH_PARASMAI, "tas", "tAm", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAN, ASH_PRATHAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ji", "an", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAN, ASH_MADHYAMA, ASH_EKAVACANA, ASH_PARASMAI, "sip", "H", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAN, ASH_MADHYAMA, ASH_DVIVACANA, ASH_PARASMAI, "Tas", "tam", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAN, ASH_MADHYAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ta", "ta", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAN, ASH_UTTAMA, ASH_EKAVACANA, ASH_PARASMAI, "mip", "am", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAN, ASH_UTTAMA, ASH_DVIVACANA, ASH_PARASMAI, "vas", "va", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LAN, ASH_UTTAMA, ASH_BAHUVACANA, ASH_PARASMAI, "mas", "ma", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
};

/* LOT (imperative) — Story 3.21. Endings per 3.4.86–96 substitutions. */
static const TingEntry LOT_PARASMAI[9] = {
    {ASH_LOT, ASH_PRATHAMA, ASH_EKAVACANA, ASH_PARASMAI, "tu", "tu", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LOT, ASH_PRATHAMA, ASH_DVIVACANA, ASH_PARASMAI, "tAm", "tAm", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LOT, ASH_PRATHAMA, ASH_BAHUVACANA, ASH_PARASMAI, "antu", "antu", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    /* madhyama-eka: 3.4.91 seḥ hi → "hi" but realised as "" (zero) for vowel-final stems. */
    {ASH_LOT, ASH_MADHYAMA, ASH_EKAVACANA, ASH_PARASMAI, "hi", "", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LOT, ASH_MADHYAMA, ASH_DVIVACANA, ASH_PARASMAI, "tam", "tam", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LOT, ASH_MADHYAMA, ASH_BAHUVACANA, ASH_PARASMAI, "ta", "ta", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LOT, ASH_UTTAMA, ASH_EKAVACANA, ASH_PARASMAI, "Ani", "Ani", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LOT, ASH_UTTAMA, ASH_DVIVACANA, ASH_PARASMAI, "Ava", "Ava", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_LOT, ASH_UTTAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ama", "Ama", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
};

/* VIDHILIN (optative) — Story 3.22. yāsuṭ in singular, ī in dual/plural;
   the table here records the ending after yA/I has been merged with the
   tiṅ. For thematic stems the result simplifies to e+secondary. */
static const TingEntry VIDHILIN_PARASMAI[9] = {
    {ASH_VIDHILIM, ASH_PRATHAMA, ASH_EKAVACANA, ASH_PARASMAI, "yAt", "et", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_VIDHILIM, ASH_PRATHAMA, ASH_DVIVACANA, ASH_PARASMAI, "yAtAm", "etAm", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_VIDHILIM, ASH_PRATHAMA, ASH_BAHUVACANA, ASH_PARASMAI, "yur", "eyuH", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_VIDHILIM, ASH_MADHYAMA, ASH_EKAVACANA, ASH_PARASMAI, "yAH", "eH", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_VIDHILIM, ASH_MADHYAMA, ASH_DVIVACANA, ASH_PARASMAI, "yAtam", "etam", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_VIDHILIM, ASH_MADHYAMA, ASH_BAHUVACANA, ASH_PARASMAI, "yAta", "eta", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_VIDHILIM, ASH_UTTAMA, ASH_EKAVACANA, ASH_PARASMAI, "yAm", "eyam", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_VIDHILIM, ASH_UTTAMA, ASH_DVIVACANA, ASH_PARASMAI, "yAva", "eva", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
    {ASH_VIDHILIM, ASH_UTTAMA, ASH_BAHUVACANA, ASH_PARASMAI, "yAma", "ema", SJ_TING | SJ_PARASMAIPADA | SJ_SARVADHATUKA},
};

/* LUT (periphrastic future) — Story 3.19. The endings absorb the
   tās augment so that the "stem" passed in only needs the root + iṭ.
   3.4.78 also substitutes specific upadeśa endings for prathama
   (DA, rau, ras → A, ArO, AraH). */
static const TingEntry LUT_PARASMAI[9] = {
    {ASH_LUT, ASH_PRATHAMA, ASH_EKAVACANA, ASH_PARASMAI, "DA", "tA", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LUT, ASH_PRATHAMA, ASH_DVIVACANA, ASH_PARASMAI, "rO", "tArO", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LUT, ASH_PRATHAMA, ASH_BAHUVACANA, ASH_PARASMAI, "raH", "tAraH", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LUT, ASH_MADHYAMA, ASH_EKAVACANA, ASH_PARASMAI, "sip", "tAsi", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LUT, ASH_MADHYAMA, ASH_DVIVACANA, ASH_PARASMAI, "Tas", "tAsTaH", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LUT, ASH_MADHYAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ta", "tAsTa", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LUT, ASH_UTTAMA, ASH_EKAVACANA, ASH_PARASMAI, "mip", "tAsmi", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LUT, ASH_UTTAMA, ASH_DVIVACANA, ASH_PARASMAI, "vas", "tAsvaH", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LUT, ASH_UTTAMA, ASH_BAHUVACANA, ASH_PARASMAI, "mas", "tAsmaH", SJ_TING | SJ_PARASMAIPADA},
};

/* LRN (conditional) — Story 3.25. Combines LRT's sya stem with LAN's
   secondary endings + a-augment. Endings = LAN secondary endings. */
static const TingEntry LRN_PARASMAI[9] = {
    {ASH_LRN, ASH_PRATHAMA, ASH_EKAVACANA, ASH_PARASMAI, "tip", "t", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRN, ASH_PRATHAMA, ASH_DVIVACANA, ASH_PARASMAI, "tas", "tAm", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRN, ASH_PRATHAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ji", "an", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRN, ASH_MADHYAMA, ASH_EKAVACANA, ASH_PARASMAI, "sip", "H", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRN, ASH_MADHYAMA, ASH_DVIVACANA, ASH_PARASMAI, "Tas", "tam", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRN, ASH_MADHYAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ta", "ta", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRN, ASH_UTTAMA, ASH_EKAVACANA, ASH_PARASMAI, "mip", "am", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRN, ASH_UTTAMA, ASH_DVIVACANA, ASH_PARASMAI, "vas", "va", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRN, ASH_UTTAMA, ASH_BAHUVACANA, ASH_PARASMAI, "mas", "ma", SJ_TING | SJ_PARASMAIPADA},
};

/* ASIRLIN (benedictive) — Story 3.23. yāsuṭ + sIyuṭ + secondary
   endings. The stem is bare root (suffix is kit, blocks guṇa). */
static const TingEntry ASIRLIN_PARASMAI[9] = {
    {ASH_ASHIRLIM, ASH_PRATHAMA, ASH_EKAVACANA, ASH_PARASMAI, "tip", "yAt", SJ_TING | SJ_PARASMAIPADA},
    {ASH_ASHIRLIM, ASH_PRATHAMA, ASH_DVIVACANA, ASH_PARASMAI, "tas", "yAstAm", SJ_TING | SJ_PARASMAIPADA},
    {ASH_ASHIRLIM, ASH_PRATHAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ji", "yAsuH", SJ_TING | SJ_PARASMAIPADA},
    {ASH_ASHIRLIM, ASH_MADHYAMA, ASH_EKAVACANA, ASH_PARASMAI, "sip", "yAH", SJ_TING | SJ_PARASMAIPADA},
    {ASH_ASHIRLIM, ASH_MADHYAMA, ASH_DVIVACANA, ASH_PARASMAI, "Tas", "yAstam", SJ_TING | SJ_PARASMAIPADA},
    {ASH_ASHIRLIM, ASH_MADHYAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ta", "yAsta", SJ_TING | SJ_PARASMAIPADA},
    {ASH_ASHIRLIM, ASH_UTTAMA, ASH_EKAVACANA, ASH_PARASMAI, "mip", "yAsam", SJ_TING | SJ_PARASMAIPADA},
    {ASH_ASHIRLIM, ASH_UTTAMA, ASH_DVIVACANA, ASH_PARASMAI, "vas", "yAsva", SJ_TING | SJ_PARASMAIPADA},
    {ASH_ASHIRLIM, ASH_UTTAMA, ASH_BAHUVACANA, ASH_PARASMAI, "mas", "yAsma", SJ_TING | SJ_PARASMAIPADA},
};

/* LIT (perfect) — Story 3.18. Endings are Ṇal, atus, us, Thal,
   athuH, a, ṇal-am, va, ma. Built on the reduplicated stem. */
static const TingEntry LIT_PARASMAI[9] = {
    {ASH_LIT, ASH_PRATHAMA, ASH_EKAVACANA, ASH_PARASMAI, "Ral", "a", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LIT, ASH_PRATHAMA, ASH_DVIVACANA, ASH_PARASMAI, "atus", "atuH", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LIT, ASH_PRATHAMA, ASH_BAHUVACANA, ASH_PARASMAI, "us", "uH", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LIT, ASH_MADHYAMA, ASH_EKAVACANA, ASH_PARASMAI, "Tal", "iTa", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LIT, ASH_MADHYAMA, ASH_DVIVACANA, ASH_PARASMAI, "aTus", "aTuH", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LIT, ASH_MADHYAMA, ASH_BAHUVACANA, ASH_PARASMAI, "a", "a", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LIT, ASH_UTTAMA, ASH_EKAVACANA, ASH_PARASMAI, "Ralam", "a", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LIT, ASH_UTTAMA, ASH_DVIVACANA, ASH_PARASMAI, "va", "iva", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LIT, ASH_UTTAMA, ASH_BAHUVACANA, ASH_PARASMAI, "ma", "ima", SJ_TING | SJ_PARASMAIPADA},
};

/* LUN (aorist) — Story 3.24. Default iṣ-aorist endings (most common
   sub-class for seṭ gaṇa-1 P roots). The clean form embeds the
   iṣ-marker; the root portion is treated separately at form-build
   time (a-augment, optional guṇa). Special-class roots (root-aorist
   for bhū, sic-aorist for nī etc.) are handled inline. */
static const TingEntry LUN_PARASMAI[9] = {
    {ASH_LUN, ASH_PRATHAMA, ASH_EKAVACANA,  ASH_PARASMAI, "tip", "It",     SJ_TING | SJ_PARASMAIPADA},
    {ASH_LUN, ASH_PRATHAMA, ASH_DVIVACANA,  ASH_PARASMAI, "tas", "izwAm",  SJ_TING | SJ_PARASMAIPADA},
    {ASH_LUN, ASH_PRATHAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ji",  "izuH",   SJ_TING | SJ_PARASMAIPADA},
    {ASH_LUN, ASH_MADHYAMA, ASH_EKAVACANA,  ASH_PARASMAI, "sip", "IH",     SJ_TING | SJ_PARASMAIPADA},
    {ASH_LUN, ASH_MADHYAMA, ASH_DVIVACANA,  ASH_PARASMAI, "Tas", "izwam",  SJ_TING | SJ_PARASMAIPADA},
    {ASH_LUN, ASH_MADHYAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ta",  "izwa",   SJ_TING | SJ_PARASMAIPADA},
    {ASH_LUN, ASH_UTTAMA,   ASH_EKAVACANA,  ASH_PARASMAI, "mip", "izam",   SJ_TING | SJ_PARASMAIPADA},
    {ASH_LUN, ASH_UTTAMA,   ASH_DVIVACANA,  ASH_PARASMAI, "vas", "izva",   SJ_TING | SJ_PARASMAIPADA},
    {ASH_LUN, ASH_UTTAMA,   ASH_BAHUVACANA, ASH_PARASMAI, "mas", "izma",   SJ_TING | SJ_PARASMAIPADA},
};
static const TingEntry LUN_ATMANE[9] = {
    {ASH_LUN, ASH_PRATHAMA, ASH_EKAVACANA,  ASH_ATMANE, "ta",    "izwa",    SJ_TING | SJ_ATMANEPADA},
    {ASH_LUN, ASH_PRATHAMA, ASH_DVIVACANA,  ASH_ATMANE, "AtAm",  "izAtAm",  SJ_TING | SJ_ATMANEPADA},
    {ASH_LUN, ASH_PRATHAMA, ASH_BAHUVACANA, ASH_ATMANE, "Ja",    "izata",   SJ_TING | SJ_ATMANEPADA},
    {ASH_LUN, ASH_MADHYAMA, ASH_EKAVACANA,  ASH_ATMANE, "TAs",   "izWAH",   SJ_TING | SJ_ATMANEPADA},
    {ASH_LUN, ASH_MADHYAMA, ASH_DVIVACANA,  ASH_ATMANE, "ATAm",  "izATAm",  SJ_TING | SJ_ATMANEPADA},
    {ASH_LUN, ASH_MADHYAMA, ASH_BAHUVACANA, ASH_ATMANE, "Dvam",  "iDvam",   SJ_TING | SJ_ATMANEPADA},
    {ASH_LUN, ASH_UTTAMA,   ASH_EKAVACANA,  ASH_ATMANE, "iw",    "izi",     SJ_TING | SJ_ATMANEPADA},
    {ASH_LUN, ASH_UTTAMA,   ASH_DVIVACANA,  ASH_ATMANE, "vahi",  "izvahi",  SJ_TING | SJ_ATMANEPADA},
    {ASH_LUN, ASH_UTTAMA,   ASH_BAHUVACANA, ASH_ATMANE, "mahiN", "izmahi",  SJ_TING | SJ_ATMANEPADA},
};

/* LRT (simple future) — Story 3.20. Same endings as LAT (primary). */
static const TingEntry LRT_PARASMAI[9] = {
    {ASH_LRT, ASH_PRATHAMA, ASH_EKAVACANA, ASH_PARASMAI, "tip", "ti", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRT, ASH_PRATHAMA, ASH_DVIVACANA, ASH_PARASMAI, "tas", "tas", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRT, ASH_PRATHAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ji", "anti", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRT, ASH_MADHYAMA, ASH_EKAVACANA, ASH_PARASMAI, "sip", "si", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRT, ASH_MADHYAMA, ASH_DVIVACANA, ASH_PARASMAI, "Tas", "Tas", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRT, ASH_MADHYAMA, ASH_BAHUVACANA, ASH_PARASMAI, "Ta", "Ta", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRT, ASH_UTTAMA, ASH_EKAVACANA, ASH_PARASMAI, "mip", "mi", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRT, ASH_UTTAMA, ASH_DVIVACANA, ASH_PARASMAI, "vas", "vas", SJ_TING | SJ_PARASMAIPADA},
    {ASH_LRT, ASH_UTTAMA, ASH_BAHUVACANA, ASH_PARASMAI, "mas", "mas", SJ_TING | SJ_PARASMAIPADA},
};

/* Ā (ātmanepada) endings for LIT/LUT/LRT/LOT/LAN/VIDHILIM/ASHIRLIM/LRN.
   Clean forms are derived from BORI dhātu-forms (gaṇa-1 BAza paradigm)
   after subtracting the stem. The stem-final 'a' triggers a + e → e
   merge for endings starting with 'e' and a + A → A merge for endings
   starting with 'A' (already handled at the stem→ending boundary). */
static const TingEntry LIT_ATMANE[9] = {
    {ASH_LIT, ASH_PRATHAMA,  ASH_EKAVACANA,   ASH_ATMANE, "eS",    "e",      SJ_TING | SJ_ATMANEPADA},
    {ASH_LIT, ASH_PRATHAMA,  ASH_DVIVACANA,   ASH_ATMANE, "AtAm",  "Ate",    SJ_TING | SJ_ATMANEPADA},
    {ASH_LIT, ASH_PRATHAMA,  ASH_BAHUVACANA,  ASH_ATMANE, "JiC",   "ire",    SJ_TING | SJ_ATMANEPADA},
    {ASH_LIT, ASH_MADHYAMA,  ASH_EKAVACANA,   ASH_ATMANE, "se",    "ize",    SJ_TING | SJ_ATMANEPADA},
    {ASH_LIT, ASH_MADHYAMA,  ASH_DVIVACANA,   ASH_ATMANE, "ATAm",  "ATe",    SJ_TING | SJ_ATMANEPADA},
    {ASH_LIT, ASH_MADHYAMA,  ASH_BAHUVACANA,  ASH_ATMANE, "Dve",   "iDve",   SJ_TING | SJ_ATMANEPADA},
    {ASH_LIT, ASH_UTTAMA,    ASH_EKAVACANA,   ASH_ATMANE, "eS",    "e",      SJ_TING | SJ_ATMANEPADA},
    {ASH_LIT, ASH_UTTAMA,    ASH_DVIVACANA,   ASH_ATMANE, "vahe",  "ivahe",  SJ_TING | SJ_ATMANEPADA},
    {ASH_LIT, ASH_UTTAMA,    ASH_BAHUVACANA,  ASH_ATMANE, "mahiN", "imahe",  SJ_TING | SJ_ATMANEPADA},
};
static const TingEntry LUT_ATMANE[9] = {
    {ASH_LUT, ASH_PRATHAMA,  ASH_EKAVACANA,   ASH_ATMANE, "DA",    "tA",      SJ_TING | SJ_ATMANEPADA},
    {ASH_LUT, ASH_PRATHAMA,  ASH_DVIVACANA,   ASH_ATMANE, "rO",    "tArO",    SJ_TING | SJ_ATMANEPADA},
    {ASH_LUT, ASH_PRATHAMA,  ASH_BAHUVACANA,  ASH_ATMANE, "raH",   "tAraH",   SJ_TING | SJ_ATMANEPADA},
    {ASH_LUT, ASH_MADHYAMA,  ASH_EKAVACANA,   ASH_ATMANE, "TAse",  "tAse",    SJ_TING | SJ_ATMANEPADA},
    {ASH_LUT, ASH_MADHYAMA,  ASH_DVIVACANA,   ASH_ATMANE, "ATAm",  "tAsATe",  SJ_TING | SJ_ATMANEPADA},
    {ASH_LUT, ASH_MADHYAMA,  ASH_BAHUVACANA,  ASH_ATMANE, "Dve",   "tADve",   SJ_TING | SJ_ATMANEPADA},
    {ASH_LUT, ASH_UTTAMA,    ASH_EKAVACANA,   ASH_ATMANE, "iw",    "tAhe",    SJ_TING | SJ_ATMANEPADA},
    {ASH_LUT, ASH_UTTAMA,    ASH_DVIVACANA,   ASH_ATMANE, "vahe",  "tAsvahe", SJ_TING | SJ_ATMANEPADA},
    {ASH_LUT, ASH_UTTAMA,    ASH_BAHUVACANA,  ASH_ATMANE, "mahe",  "tAsmahe", SJ_TING | SJ_ATMANEPADA},
};
/* LRT_A and LAT_A share endings (sya stem already added at vikaraṇa). */
static const TingEntry LRT_ATMANE[9] = {
    {ASH_LRT, ASH_PRATHAMA,  ASH_EKAVACANA,   ASH_ATMANE, "ta",    "te",     SJ_TING | SJ_ATMANEPADA},
    {ASH_LRT, ASH_PRATHAMA,  ASH_DVIVACANA,   ASH_ATMANE, "AtAm",  "ete",    SJ_TING | SJ_ATMANEPADA},
    {ASH_LRT, ASH_PRATHAMA,  ASH_BAHUVACANA,  ASH_ATMANE, "Ja",    "ante",   SJ_TING | SJ_ATMANEPADA},
    {ASH_LRT, ASH_MADHYAMA,  ASH_EKAVACANA,   ASH_ATMANE, "TAs",   "se",     SJ_TING | SJ_ATMANEPADA},
    {ASH_LRT, ASH_MADHYAMA,  ASH_DVIVACANA,   ASH_ATMANE, "ATAm",  "eTe",    SJ_TING | SJ_ATMANEPADA},
    {ASH_LRT, ASH_MADHYAMA,  ASH_BAHUVACANA,  ASH_ATMANE, "Dvam",  "Dve",    SJ_TING | SJ_ATMANEPADA},
    {ASH_LRT, ASH_UTTAMA,    ASH_EKAVACANA,   ASH_ATMANE, "iw",    "e",      SJ_TING | SJ_ATMANEPADA},
    {ASH_LRT, ASH_UTTAMA,    ASH_DVIVACANA,   ASH_ATMANE, "vahi",  "vahe",   SJ_TING | SJ_ATMANEPADA},
    {ASH_LRT, ASH_UTTAMA,    ASH_BAHUVACANA,  ASH_ATMANE, "mahiN", "mahe",   SJ_TING | SJ_ATMANEPADA},
};
/* LOT (imperative) Ā. */
static const TingEntry LOT_ATMANE[9] = {
    {ASH_LOT, ASH_PRATHAMA,  ASH_EKAVACANA,   ASH_ATMANE, "tAm",   "tAm",    SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LOT, ASH_PRATHAMA,  ASH_DVIVACANA,   ASH_ATMANE, "AtAm",  "etAm",   SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LOT, ASH_PRATHAMA,  ASH_BAHUVACANA,  ASH_ATMANE, "antAm", "antAm",  SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LOT, ASH_MADHYAMA,  ASH_EKAVACANA,   ASH_ATMANE, "sva",   "sva",    SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LOT, ASH_MADHYAMA,  ASH_DVIVACANA,   ASH_ATMANE, "ATAm",  "eTAm",   SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LOT, ASH_MADHYAMA,  ASH_BAHUVACANA,  ASH_ATMANE, "Dvam",  "Dvam",   SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LOT, ASH_UTTAMA,    ASH_EKAVACANA,   ASH_ATMANE, "E",     "E",      SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LOT, ASH_UTTAMA,    ASH_DVIVACANA,   ASH_ATMANE, "AvahE", "AvahE",  SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LOT, ASH_UTTAMA,    ASH_BAHUVACANA,  ASH_ATMANE, "AmahE", "AmahE",  SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
};
/* LAN (imperfect) Ā — secondary endings; a-augment added at form-build. */
static const TingEntry LAN_ATMANE[9] = {
    {ASH_LAN, ASH_PRATHAMA,  ASH_EKAVACANA,   ASH_ATMANE, "ta",    "ta",     SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LAN, ASH_PRATHAMA,  ASH_DVIVACANA,   ASH_ATMANE, "AtAm",  "etAm",   SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LAN, ASH_PRATHAMA,  ASH_BAHUVACANA,  ASH_ATMANE, "Ja",    "anta",   SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LAN, ASH_MADHYAMA,  ASH_EKAVACANA,   ASH_ATMANE, "TAs",   "TAH",    SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LAN, ASH_MADHYAMA,  ASH_DVIVACANA,   ASH_ATMANE, "ATAm",  "eTAm",   SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LAN, ASH_MADHYAMA,  ASH_BAHUVACANA,  ASH_ATMANE, "Dvam",  "Dvam",   SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LAN, ASH_UTTAMA,    ASH_EKAVACANA,   ASH_ATMANE, "i",     "e",      SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LAN, ASH_UTTAMA,    ASH_DVIVACANA,   ASH_ATMANE, "vahi",  "vahi",   SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_LAN, ASH_UTTAMA,    ASH_BAHUVACANA,  ASH_ATMANE, "mahiN", "mahi",   SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
};
/* VIDHILIM (optative) Ā — sārvadhātuka, yāsuṭ + secondary endings. */
static const TingEntry VIDHILIN_ATMANE[9] = {
    {ASH_VIDHILIM, ASH_PRATHAMA,  ASH_EKAVACANA,   ASH_ATMANE, "Ita",     "eta",      SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_VIDHILIM, ASH_PRATHAMA,  ASH_DVIVACANA,   ASH_ATMANE, "IyAtAm",  "eyAtAm",   SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_VIDHILIM, ASH_PRATHAMA,  ASH_BAHUVACANA,  ASH_ATMANE, "Iran",    "eran",     SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_VIDHILIM, ASH_MADHYAMA,  ASH_EKAVACANA,   ASH_ATMANE, "ITAH",    "eTAH",     SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_VIDHILIM, ASH_MADHYAMA,  ASH_DVIVACANA,   ASH_ATMANE, "IyATAm",  "eyATAm",   SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_VIDHILIM, ASH_MADHYAMA,  ASH_BAHUVACANA,  ASH_ATMANE, "IDvam",   "eDvam",    SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_VIDHILIM, ASH_UTTAMA,    ASH_EKAVACANA,   ASH_ATMANE, "Iya",     "eya",      SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_VIDHILIM, ASH_UTTAMA,    ASH_DVIVACANA,   ASH_ATMANE, "Ivahi",   "evahi",    SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
    {ASH_VIDHILIM, ASH_UTTAMA,    ASH_BAHUVACANA,  ASH_ATMANE, "Imahi",   "emahi",    SJ_TING | SJ_ATMANEPADA | SJ_SARVADHATUKA},
};
/* ASHIRLIM (benedictive) Ā. */
static const TingEntry ASIRLIN_ATMANE[9] = {
    {ASH_ASHIRLIM, ASH_PRATHAMA,  ASH_EKAVACANA,   ASH_ATMANE, "ta",    "izIzwa",     SJ_TING | SJ_ATMANEPADA},
    {ASH_ASHIRLIM, ASH_PRATHAMA,  ASH_DVIVACANA,   ASH_ATMANE, "AtAm",  "izIyAstAm",  SJ_TING | SJ_ATMANEPADA},
    {ASH_ASHIRLIM, ASH_PRATHAMA,  ASH_BAHUVACANA,  ASH_ATMANE, "Ja",    "izIran",     SJ_TING | SJ_ATMANEPADA},
    {ASH_ASHIRLIM, ASH_MADHYAMA,  ASH_EKAVACANA,   ASH_ATMANE, "TAs",   "izIzWAH",    SJ_TING | SJ_ATMANEPADA},
    {ASH_ASHIRLIM, ASH_MADHYAMA,  ASH_DVIVACANA,   ASH_ATMANE, "ATAm",  "izIyAsTAm",  SJ_TING | SJ_ATMANEPADA},
    {ASH_ASHIRLIM, ASH_MADHYAMA,  ASH_BAHUVACANA,  ASH_ATMANE, "Dvam",  "izIDvam",    SJ_TING | SJ_ATMANEPADA},
    {ASH_ASHIRLIM, ASH_UTTAMA,    ASH_EKAVACANA,   ASH_ATMANE, "iw",    "izIya",      SJ_TING | SJ_ATMANEPADA},
    {ASH_ASHIRLIM, ASH_UTTAMA,    ASH_DVIVACANA,   ASH_ATMANE, "vahi",  "izIvahi",    SJ_TING | SJ_ATMANEPADA},
    {ASH_ASHIRLIM, ASH_UTTAMA,    ASH_BAHUVACANA,  ASH_ATMANE, "mahi",  "izImahi",    SJ_TING | SJ_ATMANEPADA},
};
/* LRN (conditional) Ā — LAN Ā secondary endings on sya stem with a-aug.
   The conditional stem ends in 'a' (sya), so 1dvi/2dvi merge a+A → e. */
static const TingEntry LRN_ATMANE[9] = {
    {ASH_LRN, ASH_PRATHAMA,  ASH_EKAVACANA,   ASH_ATMANE, "ta",    "ta",     SJ_TING | SJ_ATMANEPADA},
    {ASH_LRN, ASH_PRATHAMA,  ASH_DVIVACANA,   ASH_ATMANE, "AtAm",  "etAm",   SJ_TING | SJ_ATMANEPADA},
    {ASH_LRN, ASH_PRATHAMA,  ASH_BAHUVACANA,  ASH_ATMANE, "Ja",    "anta",   SJ_TING | SJ_ATMANEPADA},
    {ASH_LRN, ASH_MADHYAMA,  ASH_EKAVACANA,   ASH_ATMANE, "TAs",   "TAH",    SJ_TING | SJ_ATMANEPADA},
    {ASH_LRN, ASH_MADHYAMA,  ASH_DVIVACANA,   ASH_ATMANE, "ATAm",  "eTAm",   SJ_TING | SJ_ATMANEPADA},
    {ASH_LRN, ASH_MADHYAMA,  ASH_BAHUVACANA,  ASH_ATMANE, "Dvam",  "Dvam",   SJ_TING | SJ_ATMANEPADA},
    {ASH_LRN, ASH_UTTAMA,    ASH_EKAVACANA,   ASH_ATMANE, "i",     "e",      SJ_TING | SJ_ATMANEPADA},
    {ASH_LRN, ASH_UTTAMA,    ASH_DVIVACANA,   ASH_ATMANE, "vahi",  "vahi",   SJ_TING | SJ_ATMANEPADA},
    {ASH_LRN, ASH_UTTAMA,    ASH_BAHUVACANA,  ASH_ATMANE, "mahiN", "mahi",   SJ_TING | SJ_ATMANEPADA},
};

static int ting_index(ASH_Purusha p, ASH_Vacana v) {
  return ((int)p * 3) + (int)v;
}

const TingEntry *ting_get(ASH_Lakara l, ASH_Purusha p, ASH_Vacana v, ASH_Pada pd) {
  if (p > ASH_UTTAMA || v > ASH_BAHUVACANA) return NULL;
  int idx = ting_index(p, v);
  if (idx < 0 || idx >= 9) return NULL;
  if (pd == ASH_ATMANE) {
    switch (l) {
      case ASH_LAT:      return &LAT_ATMANE[idx];
      case ASH_LIT:      return &LIT_ATMANE[idx];
      case ASH_LUT:      return &LUT_ATMANE[idx];
      case ASH_LRT:      return &LRT_ATMANE[idx];
      case ASH_LOT:      return &LOT_ATMANE[idx];
      case ASH_LAN:      return &LAN_ATMANE[idx];
      case ASH_VIDHILIM: return &VIDHILIN_ATMANE[idx];
      case ASH_ASHIRLIM: return &ASIRLIN_ATMANE[idx];
      case ASH_LRN:      return &LRN_ATMANE[idx];
      case ASH_LUN:      return &LUN_ATMANE[idx];
      default: return NULL;
    }
  }
  switch (l) {
    case ASH_LAT:      return &LAT_PARASMAI[idx];
    case ASH_LAN:      return &LAN_PARASMAI[idx];
    case ASH_LOT:      return &LOT_PARASMAI[idx];
    case ASH_VIDHILIM: return &VIDHILIN_PARASMAI[idx];
    case ASH_LRT:      return &LRT_PARASMAI[idx];
    case ASH_LUT:      return &LUT_PARASMAI[idx];
    case ASH_LRN:      return &LRN_PARASMAI[idx];
    case ASH_ASHIRLIM: return &ASIRLIN_PARASMAI[idx];
    case ASH_LIT:      return &LIT_PARASMAI[idx];
    case ASH_LUN:      return &LUN_PARASMAI[idx];
    default: return NULL;
  }
}

int ting_assign(PrakriyaCtx *ctx, ASH_Lakara l, ASH_Purusha p, ASH_Vacana v, ASH_Pada pd) {
  if (!ctx || ctx->term_count >= MAX_TERMS) return -1;
  const TingEntry *t = ting_get(l, p, v, pd);
  if (!t) return -1;

  Term *dst = &ctx->terms[ctx->term_count];
  term_init(dst, t->upadesa, SJ_PRATYAYA | SJ_TING);
  dst->samjna = samjna_add(dst->samjna, t->samjna);

  /* Ensure the clean form matches our target table for determinism. */
  strncpy(dst->value, t->clean, TERM_VALUE_LEN - 1);
  dst->value[TERM_VALUE_LEN - 1] = '\0';

  ctx->term_count++;
  return 0;
}

bool lakara_is_sarvadhatuka(ASH_Lakara l) {
  return (l == ASH_LAT || l == ASH_LOT || l == ASH_LAN || l == ASH_VIDHILIM);
}

const char *lakara_name(ASH_Lakara l) {
  static const char *const names[] = {
      "laT", "liT", "luT", "lfT", "loT", "laN", "viDiliN", "ASIrliN", "luN", "lfN"};
  if (l < 0 || l >= ASH_LAKARA_COUNT) return "unknown";
  return names[(int)l];
}
