#!/usr/bin/env python3
"""
ingest_source.py — Parse Ashtadhyayi Sutrapatha into TSV.

Source: github.com/ashtadhyayi-com/data  (sutraani/data.txt)

REAL SCHEMA (confirmed by inspection):
  { "name": "sutraani", "data": [
      { "i": "11001",        <- encoded id: adhyaya*10000+pada*1000+num
        "a": "1",            <- adhyaya (chapter)
        "p": "1",            <- pada (quarter)
        "n": "1",            <- sutra number within pada
        "s": "वृद्धिरादैच्",  <- Devanagari sutra text
        "e": "vruddhiraadaich", <- loose romanization (NOT SLP1)
        "type": "S$...$",   <- type marker: S=samjna P=paribhasha A=adhikara
        "rpn": "1"           <- running serial (use as global_id)
        ...
      }, ...
  ]}

Total in repo: 3983 sutras (BORI edition).

Usage:
  python3 tools/ingest_source.py           # generate data/sutras.tsv
  python3 tools/ingest_source.py --validate # validate existing TSV
"""

import argparse, csv, json, os, sys, unicodedata

RAW_BASE   = "https://raw.githubusercontent.com/ashtadhyayi-com/data/master"
SUTRA_URL  = f"{RAW_BASE}/sutraani/data.txt"
FALLBACK   = os.path.join(os.path.dirname(__file__), "../vendor/sutra_fallback.json")
OUTPUT_TSV = os.path.join(os.path.dirname(__file__), "../data/sutras.tsv")
OUTPUT_H   = os.path.join(os.path.dirname(__file__), "../vendor/sutras_count.h")

# ── Devanagari → SLP1 ────────────────────────────────────────────────────────
DEVA_TO_SLP1 = {
    'अ':'a','आ':'A','इ':'i','ई':'I','उ':'u','ऊ':'U',
    'ऋ':'f','ॠ':'F','ऌ':'x','ॡ':'X',
    'ए':'e','ऐ':'E','ओ':'o','औ':'O',
    'ं':'M','ः':'H','ँ':'~',
    'क':'k','ख':'K','ग':'g','घ':'G','ङ':'N',
    'च':'c','छ':'C','ज':'j','झ':'J','ञ':'Y',
    'ट':'w','ठ':'W','ड':'q','ढ':'Q','ण':'R',
    'त':'t','थ':'T','द':'d','ध':'D','न':'n',
    'प':'p','फ':'P','ब':'b','भ':'B','म':'m',
    'य':'y','र':'r','ल':'l','व':'v',
    'श':'S','ष':'z','स':'s','ह':'h',
    'ा':'A','ि':'i','ी':'I','ु':'u','ू':'U',
    'ृ':'f','ॄ':'F','े':'e','ै':'E','ो':'o','ौ':'O',
    '्':'',  # virama — strip (halanta)
}

def deva_to_slp1(text: str) -> str:
    text = unicodedata.normalize('NFC', text)
    result = []
    for ch in text:
        if ch in DEVA_TO_SLP1:
            result.append(DEVA_TO_SLP1[ch])
        elif ord(ch) < 128:
            result.append(ch)
        # else: skip punctuation/other Devanagari glyphs
    return ''.join(result)

TYPE_MAP = {'S':'SAMJNA','P':'PARIBHASHA','A':'ADHIKARA',
            'V':'VIDHI','N':'NIYAMA','T':'ATIDESHA','I':'NISHEDHA'}

def parse_type(type_str: str) -> str:
    if not type_str:
        return 'VIDHI'
    prefix = type_str.strip()[0].upper()
    return TYPE_MAP.get(prefix, 'VIDHI')


def fetch_data() -> dict:
    if os.path.exists(FALLBACK):
        with open(FALLBACK, encoding='utf-8') as f:
            return json.load(f)
    try:
        import urllib.request
        print(f"Fetching {SUTRA_URL} ...", file=sys.stderr)
        with urllib.request.urlopen(SUTRA_URL, timeout=30) as resp:
            data = json.loads(resp.read())
        os.makedirs(os.path.dirname(FALLBACK), exist_ok=True)
        with open(FALLBACK, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        return data
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)


def generate(data: dict):
    entries = data.get('data', [])
    os.makedirs(os.path.dirname(OUTPUT_TSV), exist_ok=True)
    count = 0
    with open(OUTPUT_TSV, 'w', encoding='utf-8', newline='') as f:
        writer = csv.writer(f, delimiter='\t', quoting=csv.QUOTE_MINIMAL)
        writer.writerow(['global_id','adhyaya','pada','num',
                          'text_deva','text_slp1','sutra_type'])
        for entry in entries:
            try:
                adhyaya   = int(entry['a'])
                pada      = int(entry['p'])
                num       = int(entry['n'])
                rpn       = count + 1  # use sequential serial; entry["rpn"] is traditional ordering (has gaps)
                text_deva = unicodedata.normalize('NFC', str(entry.get('s', '')))
                text_slp1 = deva_to_slp1(text_deva)
                stype     = parse_type(entry.get('type', ''))
                count    += 1
                writer.writerow([rpn, adhyaya, pada, num,
                                  text_deva, text_slp1, stype])
            except (ValueError, KeyError) as e:
                print(f"  SKIP {entry.get('i','?')}: {e}", file=sys.stderr)

    os.makedirs(os.path.dirname(OUTPUT_H), exist_ok=True)
    with open(OUTPUT_H, 'w', encoding='utf-8') as f:
        f.write("/* Auto-generated by tools/ingest_source.py — do not edit */\n")
        f.write(f"#define ASH_SUTRA_COUNT {count}\n")
        f.write("#define ASH_SUTRA_TRADITIONAL_COUNT 3959\n")
        f.write("#define ASH_SUTRA_BORI_COUNT 3983\n")
    print(f"Generated {OUTPUT_TSV}: {count} sūtras")


def validate():
    if not os.path.exists(OUTPUT_TSV):
        print("ERROR: data/sutras.tsv not found."); sys.exit(1)
    count = prev_id = 0
    errors = []
    with open(OUTPUT_TSV, encoding='utf-8') as f:
        reader = csv.DictReader(f, delimiter='\t')
        for row in reader:
            count += 1
            gid = int(row['global_id'])
            if gid != prev_id + 1:
                errors.append(f"Row {count}: global_id {gid} not monotonic")
            prev_id = gid
            if not row['text_slp1'].strip():
                errors.append(f"Row {count}: empty text_slp1")
            if not (1 <= int(row['adhyaya']) <= 8):
                errors.append(f"Row {count}: adhyaya={row['adhyaya']} out of range")
    if errors:
        for e in errors[:10]: print(f"  ERROR: {e}")
        sys.exit(1)
    if count < 3959:
        print(f"FAIL: Only {count} sūtras"); sys.exit(1)
    print(f"PASS: {count} sūtras loaded and validated ✓")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--validate', action='store_true')
    args = parser.parse_args()
    if args.validate: validate()
    else: generate(fetch_data())

if __name__ == '__main__':
    main()
